version: '3.0'

services:
    odbl-node:
        image: odbl-node
        logging:
            options:
                max-size: "50m"
        ports:
            - 8080:8080
        environment:
            - PORT=8080
            - MODE=publisher
            - MONGO_HOST=mongodb
            - MONGO_PORT=27017
            - MONGO_DB=node

    mongodb:
        image: mongo:4.4.0
        container_name: mongodb
        volumes:
            - mongo_data:/data/db
        ports:
            - 27017:27017

volumes:
    mongo_data:
