version: '3.0'

services:
    odbl-auhtority:
        image: odbl-node
        logging:
            options:
                max-size: "50m"
        ports:
            - 5000:5000
        environment:
            - PORT=5000
            - NODE_ID=auth
            - NAME=Auhtority Node
            - MODE=authority
            - MONGO_HOST=mongodb
            - MONGO_PORT=27017
            - MONGO_DB=authority-node

    odbl-node01:
        image: odbl-node
        logging:
            options:
                max-size: "50m"
        ports:
            - 8081:8080
        environment:
            - PORT=8080
            - NODE_ID=node01
            - NAME=Node 01
            - URL=http://odbl-node01:8080
            - TACT=500
            - AUTHORITY_NODE=http://odbl-auhtority:5000
            - MODE=publisher
            - MONGO_HOST=mongodb
            - MONGO_PORT=27017
            - MONGO_DB=node01

    odbl-node02:
        image: odbl-node
        logging:
            options:
                max-size: "50m"
        ports:
            - 8082:8080
        environment:
            - PORT=8080
            - NODE_ID=node02
            - NAME=Node 02
            - URL=http://odbl-node02:8080
            - TACT=500
            - AUTHORITY_NODE=http://odbl-auhtority:5000
            - MODE=publisher
            - MONGO_HOST=mongodb
            - MONGO_PORT=27017
            - MONGO_DB=node02

    odbl-node03:
        image: odbl-node
        logging:
            options:
                max-size: "50m"
        ports:
            - 8083:8080
        environment:
            - PORT=8080
            - NODE_ID=node03
            - NAME=Node 03
            - URL=http://odbl-node03:8080
            - TACT=500
            - AUTHORITY_NODE=http://odbl-auhtority:5000
            - MODE=publisher
            - MONGO_HOST=mongodb
            - MONGO_PORT=27017
            - MONGO_DB=node03

    odbl-node04:
        image: odbl-node
        logging:
            options:
                max-size: "50m"
        ports:
            - 8084:8080
        environment:
            - PORT=8080
            - NODE_ID=node04
            - NAME=Node 04
            - URL=http://odbl-node04:8080
            - TACT=500
            - AUTHORITY_NODE=http://odbl-auhtority:5000
            - MODE=publisher
            - MONGO_HOST=mongodb
            - MONGO_PORT=27017
            - MONGO_DB=node04

    mongodb:
        image: mongo:4.4.0
        container_name: mongodb
        volumes:
            - mongo_data:/data/db
        ports:
            - 27017:27017

volumes:
    mongo_data:
